name: Functions
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: This is step1 
      run: |
        echo "${{ toJson(github) }}"
        echo "${{ github.ref }}"
        echo "${{ github.event.workflow }}"
  