name: Functions
on: workflow_dispatch
env:
  apptype: IOS
  onwer: Smaranit
jobs:
  job1:
    env:
      owner: Sheshivardhan
      env_type: dev      
    runs-on: ubuntu-latest
    steps:
    - name: This is step1 
      run: |
        echo "${{ toJson(github) }}"
        echo "${{ github.ref }}"
        echo "${{ github.event.workflow }}"
        echo "${{ toJson(env) }}"
  