name: Conditions
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: This is step1
      run: | 
         echo "${{ github.actor }}"
         echo " Hello World"
    - name: This is step2  
      if: 10==100
      run:
         echo :This is Test Step2"
    - name: This is step3  
      run:
        echo :This is Test Step3"      