name: Conditions
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      run: | 
         echo "${{ github.actor }}"
         echo " Hello World"
         echo "${{ github.ref }}"
         echo "${{ github.ref_name }}"
    - name: Build 
      run: |
         echo "This is Test Step2"
    - name: Deploy  
      if: github.ref_name =='master' 
      run:
        echo "This is Test Step3"      
        
         