name: Functions-1
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
    - name: This is Step1
      run: |
          echo " This is Step1"
    - name: This is Step2   
      run: |
         echo " This is Step2"   
         sleep 15
         exit 1
    - name: This is Step3
      if : ${{ failure() }}    
      run: |
         echo " This is Step3"   
         sleep 15
         
            
