name: wf-matrix
on: workflow_dispatch
jobs:
  jobx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        swver:
        - "3.10"
        - "3.11"
        - "3.12"
    steps:
    - name: checkout the code
      uses: actions/checkout@v6
    - name: Display File
      run: |
          pwd
          ls -l
    - name: Set Up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.swver }}  
    - name: Run Application
      run: |
         python HelloWorld.py
    
      
      
      
     
      