name: wf-matrix
on: workflow_dispatch
jobs:
  jobx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - window-latest
        swver:
        - "3.10"
        - "3.11"
        - "3.12"
    steps:
    - name: print msg
      shell: bash
      run: |
         echo "This is  ${{ matrix.os }}-${{ matrix.swver }}"


github.ref
github.actor
runner.os