name: Image Build
on: workflow_dispatch
env:
  DUSER: ${{ github.repository_owner }}
  DR_PASSWD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout the Code
      run: |
         echo "Before Clone"
         pwd
         ls -lrt
         git clone https://github.com/svreddy50/may25.git
         echo "After Clone"
         ls -lrt
         cd may25
         ls -lrt
         pwd
    - name: Application Build
      run: |
         echo "Application Build Started"
         echo "Application Build Complted"
    - name: Image build
      working-directory: ./may25
      run: |
        pwd
        docker build -t ghcr.io/${{ env.DUSER }}/imagex:vx .
        docker images
    - name: Image Push 
      run: |
         docker login ghcr.io -u ${{ env.DUSER }} -p ${{ env.DR_PASSWD }}
         docker push ghcr.io/${{ env.DUSER }}/imagex:vx
                  
          
         