name: Image Build
on: workflow_dispatch
env:
  DUSER: ${{ vars.DUSERNAME }}
  DR_PASSWD: ${{ secrets.DOCKER_REG }}
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Code
      run: |
         echo "Before Clone"
         pwd
         ls -lrt
         git clone https://github.com/svreddy50/may25.git
         echo "After Clone"
         ls -lrt
         cd may25
         ls -lrt
         pwd
    - name: Application Build
      run: |
         echo "Application Build Started"
         echo "Application Build Complted"
    - name: Image build
      run: |
        cd may25
        docker build -t docker.io/${{ env.DUSER }}/imagex:vx .
        docker images
    - name: Image Push 
      run: |
         docker login -u ${{ env.DUSER }} -p ${{ env.DR_PASSWD }}
         docker push docker.io/${{ env.DUSER }}/imagex:vx
                  
          
         